# print("EJERCICIO 1")
# nom_producto= input("ingresa el nombre de tu producto: ")
# precio_unitario= float(input("ingresa el precio unitario de ese producto:"))
# cantidad = int(input("ingresa la cantidad del producto: "))
# tupla = (nom_producto,precio_unitario,)
# lista = [tupla,cantidad]
# dicionario = { "producto":lista
#               }
# cf= precio_unitario * cantidad
# print("si precio total del producto es: ",cf)

# print("------------------------------------------------------------------------------------\n")
# print("EJERCICIO 2")
# print("COMPRA DE PRODUCTOS")
# print("primer producto\n")
# primer_producto_1 = input("ingresa el primer producto comprado: ")
# precio_uni_1= float(input("ingrese precio unitario del primer producto: "))
# cantidad_1 = int(input("ingresa la cantidad comprada: "))
# print("SEGUNDO PRODUCTO\n")
# segundo_producto_2 = input("ingresa el segundo producto comprado: ")
# precio_uni_2 = float(input("ingrese precio unitario del segundo producto: "))
# cantidad_2 = int(input("ingresa la cantidad comprada: "))
# print("TERCER PRODUCTO\n")
# primer_producto_3 = input("ingresa el tercer producto comprado: ")
# precio_uni_3 = float(input("ingrese precio unitario del tercer producto: "))
# cantidad_3 = int(input("ingresa la cantidad comprada: "))
# tupla_1 =()
