# print("*******TALLER DE CONDICIONALES Y DIAGRAMAS DE FLUJO*********")

# print("Ejercicios con condicionaeles y operaciones matematicas\n")
# print("EJERCICIO 1")
# numero = float(input("ingresa un numero para verificar si es positivo,negativo o cero: "))
# if numero > 0 :
#     print("el numero es positvo")
# elif numero < 0 : 
#     print("el numero es negativo")
# else : 
#     print("el numero es cero")

# print("EJERCICIO 2")
# n1 = float(input("Ingrese un priemr numero: "))
# n2 = float(input("Ingrese un segundo numero: "))
# if n1 > n2 : 
#     print("el primer numero es mayor")
# elif n1 < n2 : 
#     print("el segundo numero es mayor")
# else : 
#     print("esta obsion no esta disponible")

# print("EJERCICIO 3")

# print("Ejercicio 4")
# numero = int(input("ingrese un numero: "))
# if numero > 10 and numero < 20 : 
#     print("su numero esta entre el 10 y el 20")
# else :
#     print("su numero no forma parte de los numeros selecionados")
    

# print("Ejercicio 5")
# n1 = int(input("ingrese un primero numero: "))
# n2 = int(input("Ingrese un segundo numero: "))
# n3 = int(input("Ingrese un tercer numero: "))
# if n1 > n2 and n1 > n3 :
#     print("el primer numero es mayor que el resto")
# elif n2 > n1 and n2 >n3 :
#     print("el segundo numero es mayor que el resto")
# elif n3 > n1 and n3 > n2 :
#     print("el tercer numero es mayor que el resto")
    
# print("Ejercicio 6")
